### ISSUE TITLE
when I npm publish offline, store the current state and publish that

### ISSUE THREAD

**Issue by thlorenz** [feross/cyberhobo#1]
Currently it'd publish what is in my dir the moment I get connected instead of what was in it when I called `npm pub` initially.
So we need to store the current state of the dir somehow and here is an easy way to accomplish that, quoting from irc:

> feross: I got it, just call `npm pack`, store the resulting tgz and then publish that later

**Comment by feross** [comment]
Yeah, this is a good idea!

**Comment by feross** [comment]
I don't really intend to implement this, so I'm going to close it. If anyone sees this later, PR welcome! Cleaning up old issues :)
